uploads = []

[[generated]]
id = "tpQU_Iah7GiEz4hFYJ67V"
uri = "file://static/agvisor_tractor_logo.png"
type = "image"
title = "agvisor tractor logo"

[[generated]]
id = "o9m-CTde0XJZqDOBeQN7d"
uri = "file://static/agvisor_logo.png"
type = "image"
title = "agvisor green circle gold tractor logo"

[[outputs]]
id = "tBq_KDLLhgdWNKr0brgiI"
uri = "file://static/agvisor_tractor_logo.png"
type = "image"
title = "Agvisor Tractor Logo"

[[outputs]]
id = "YcyYPNIhgvNkZfnRnvrbH"
uri = "file://static/agvisor_logo.png"
type = "image"
title = "Agvisor Logo — Gold Tractor on Green"
